### PR TITLE
Add firefox support

### PR DESCRIPTION
**Pull request by wesbos**
Firefox doesn't support the permissions `name: microphone`, but setting to granted just prompts the user to allow access. Denying a mic seems to work just fine and doesn't pipe the audio in.

A side: Maybe this could be opt-in per mic. Getting 1 micrphone should give you the list of mics, and then clicking the other mics, should prompt the user. I have lik 12 mics and its a bit much haha.

Screenshot 2023-02-27 at 10 53 32 AM

The above also found a bug where it's possible that you would set undefined to localStorage, which would make it truthy string of undefined.

### CODE REVIEW

**Comment by THowland1** [comment]
Me to me about `name: 'microphone'`
image

**Comment by THowland1** [comment]
Good catch on the `undefined` bug with `persistedWritable`, especially useful given that this is not my only project that uses it 😟

**Comment by THowland1** [comment]
Good point about the opt-in per-microphone. I didn't spot that friction point initially due to Chromium bias. I reckon I could make something work elegantly

**Comment by wesbos** [comment]
haha - looks like the types are taken from Firefox ` "geolocation" | "notifications" | "persistent-storage" | "push" | "screen-wake-lock" | "xr-spatial-tracking"`

**Pull request merged**
